name: Test API (Python)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verificar configuración Django
        run: |
          python -c "import django; print('Django version:', django.get_version())"
        env:
          DJANGO_SETTINGS_MODULE: winespa.settings
          PYTHONPATH: ${{ github.workspace }}

      - name: Ejecutar pruebas
        run: |
          python -m pytest api/usuarios/test_usuarios.py -v
        env:
          DJANGO_SETTINGS_MODULE: winespa.settings
          PYTHONPATH: ${{ github.workspace }}
          DEBUG: "True"
